### ISSUE TITLE
KeyError:'pCR'

### ISSUE THREAD

**Issue by ImageDragon520** [chenyixie123/ESCC_ML#2]
Hello,sir!
I'm running your‘ svm.py ’The following problems occurred during the process.I can't solve the problem, so I ask for your help.
Thanks!

runfile('C:/Users/15066/Desktop/ESCC_ML-master/Model construction/svm.py', wdir='C:/Users/15066/Desktop/ESCC_ML-master/Model construction')
Traceback (most recent call last):

  File "C:\Users\15066\anaconda3\envs\Python36\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)

  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'pCR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\15066\Desktop\ESCC_ML-master\Model construction\svm.py", line 17, in <module>
    y_train = data['pCR']

  File "C:\Users\15066\anaconda3\envs\Python36\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)

  File "C:\Users\15066\anaconda3\envs\Python36\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))

  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'pCR'

**Comment by ImageDragon520** [comment]
@chenyixie123

**Comment by ImageDragon520** [comment]
Could you give me some information about robust_harmonized_features_cohort1.csv @chenyixie123

**Comment by cyxie601** [comment]
The information for the robust_harmonized_features_cohort1.csv could be found in 

 ESCC_ML/Expected results/harmonized_cohort1.csv

It requires an addition of your ground truth (pCR in this case) to these harmonized features
